#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: rhasspy/wyoming-piper
  # -- image tag
  tag: 1.2.0
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Override the args for the default container
args:
  - "--voice"
  - "es-es-sharvard-medium"

# -- environment variables. See more environment variables in the [heimdall documentation](https://github.com/linuxserver/docker-heimdall#parameters).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Madrid
  
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 10200

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
