{{ if eq $.Values.token.existingSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-duckdns-webhook.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-duckdns-webhook.name" . }}
    chart: {{ include "cert-manager-duckdns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  token: "{{ $.Values.token.value}}"
{{ end }}

