---
apiVersion: v2
appVersion: 1.0.0
description: Model Context Protocol
name: mcp
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - kassio
  - mcp
home: https://github.com/masantiago/kassio-repository/tree/master/charts/mcp
maintainers:
  - name: masantiago
    email: miguelangel.santiago@hotmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
